name: internet_forensics
channels:
  - defaults
  - conda
  - conda-forge
dependencies:
  - python=3.9.7
  - pytest=6.2.5
  - pytest-cov=3.0.0
  - click=8.0.4
  - sqlite=3.38.5
  - pip=21.2.4
  - pip:
      - bcrypt==3.2.2
      - safety==2.1.1
      - -e .
