name: internet_forensics
channels:
  - defaults
  - conda
  - conda-forge
dependencies:
  - python=3.9.7
  - pytest=6.2.5
  - pytest-cov=3.0.0
  - autopep8=1.6.0
  - flake8=4.0.1
  - isort=5.9.3
  - pylint=2.14.5
  - pyyaml=6.0.0
  - click=8.0.4
  - sqlite=3.38.5
  - sqlalchemy=1.4.39
  - pip=21.2.4
  - pip:
      - bcrypt==3.2.2
      - safety==2.1.1
      - -e .
variables:
  # The environment 'ENV' variable could be either 'dev' (for development), 'test' (for testing), 'uat' (for user
  # acceptance testing), or 'prod' (for production). Based on this variable, an appropriate level for log is set,
  # i.e., 'DEBUG' for 'dev', 'INFO' for 'test', 'WARNING' for 'uat', 'ERROR' for 'prod'.
  ENV: prod
