name: internet_forensics
channels:
  - conda
  - pip
dependencies:
  - pip=21.2.4
  - pytest=6.2.5
  - pytest-cov=3.0.0
  - python=3.9.7
  - sqlite=3.38.5
  - flask=2.2.0
  - pyodbc=4.0.34
  - bcrypt=3.2.2
  - pip:
      - safety==2.1.1
